module.exports = {
  "kind": "track",
  "id": 65540182,
  "created_at": "2012/10/31 18:19:12 +0000",
  "user_id": 1143882,
  "duration": 259367,
  "commentable": true,
  "state": "finished",
  "original_content_size": 10405244,
  "sharing": "public",
  "tag_list": "hucci stookisound brighton london alltrapmusic thisistrapmusic baauer flosstradamus",
  "permalink": "hucci-stooki-sound-ball-so-hard",
  "streamable": true,
  "embeddable_by": "all",
  "downloadable": false,
  "purchase_url": null,
  "label_id": null,
  "purchase_title": null,
  "genre": "TRAP",
  "title": "Hucci x Stooki Sound - Ball So Hard",
  "description": "Teamed up with @StookiSound and we cooked this\r\n\r\n@AllTrapMusic http://www.youtube.com/watch?v=SUu0KIvTe44\r\n\r\nhttp://www.facebook.com/huccii\r\n\r\nhttp://www.facebook.com/stookisound",
  "label_name": "",
  "release": "",
  "track_type": "",
  "key_signature": "",
  "isrc": "",
  "video_url": null,
  "bpm": null,
  "release_year": null,
  "release_month": null,
  "release_day": null,
  "original_format": "mp3",
  "license": "all-rights-reserved",
  "uri": "https://api.soundcloud.com/tracks/65540182",
  "user": {
    "id": 1143882,
    "kind": "user",
    "permalink": "hucci",
    "username": "HU₵₵I",
    "uri": "https://api.soundcloud.com/users/1143882",
    "permalink_url": "http://soundcloud.com/hucci",
    "avatar_url": "https://i1.sndcdn.com/avatars-000096090932-mcbrxg-large.jpg?e76cf77"
  },
  "permalink_url": "http://soundcloud.com/hucci/hucci-stooki-sound-ball-so-hard",
  "artwork_url": "https://i1.sndcdn.com/artworks-000033246614-2h0xvi-large.jpg?e76cf77",
  "waveform_url": "https://w1.sndcdn.com/8e8rz5rHhxFq_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/65540182/stream",
  "playback_count": 1759136,
  "download_count": 0,
  "favoritings_count": 31516,
  "comment_count": 1369,
  "attachments_uri": "https://api.soundcloud.com/tracks/65540182/attachments",
  "policy": "ALLOW"
};